version: '3.4'

services:
  webapi-pub_pv:
    image: ${DOCKER_REGISTRY-}webapipubpv
    build:
      context: .
      dockerfile: WebApi-PUB_PV/Dockerfile
    environment:
      COMPOSE: "true"
    ports:
      - 5000:80
      - 5001:443
    links:
      - db

  db:
    image: postgres:13
    environment:
        POSTGRES_USER: su
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: Pub_PuertaVerde
    volumes:
        - db-webapi-agrotic-data-postgresql-compose:/var/lib/postgresql/data:Z
    ports:
        - 1300:5432

volumes:
  db-webapi-agrotic-data-postgresql-compose:
    driver: local
